name: Purge CDN Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        run: |
          curl -i https://purge.jsdelivr.net/gh/Abhisheksahu-unlink/cdn-common-components@main/common-components.js
